In [1]:
import neo

# Replace 'path_to_ns2_file.ns2' with the path to your NS2 file
reader = neo.BlackrockIO(filename='../data/datafile001.ns2')
blk = reader.read_block()

# blk contains all the data segments and signals


In [ ]:
for seg in blk.segments:
    for asig in seg.analogsignals:
        print(asig)  # This will print out the signal object which contains data


[[ -925.25  -781.75  -773.75 ... -1167.75 -8185.   -8192.  ]
 [-1218.75 -1051.75 -1041.25 ... -1480.   -8183.25 -8192.  ]
 [-1488.25 -1307.25 -1298.5  ... -1767.   -8181.75 -8192.  ]
 ...
 [ -980.5   -884.75  -895.75 ... -1130.    8191.75  8191.75]
 [ -668.5   -586.5   -601.75 ...  -779.75  8191.75  8189.75]
 [ -255.5   -244.    -263.   ...  -256.    8191.75  8187.75]] uV


In [ ]:
import pandas as pd

data = []  # This will hold all the data rows
for seg in blk.segments:
    for asig in seg.analogsignals:
        data.append(asig.magnitude.flatten())  # Convert data to a flat list

# Create a DataFrame and save to CSV
df = pd.DataFrame(data)
df.to_csv('datafile-output1.csv', index=False)


In [ ]:
 bdata = pd.read_csv('/content/datafile-output1.csv')

In [ ]:
data.head()

0       1       2       3      4       5      6      7       8  \
0 -925.25 -781.75 -773.75 -856.25 -801.0 -798.25 -725.5 -704.5 -724.25   

        9  ...  320310  320311  320312  320313  320314  320315  320316  \
0 -800.75  ... -317.75 -182.25 -181.75  -206.5  -222.5  -173.5 -147.75   

   320317   320318   320319  
0  -256.0  8191.75  8187.75  

[1 rows x 320320 columns]

In [ ]:
data.shape

(1, 320320)

In [ ]:
# You mentioned you expected a sampling rate of 1000 Hz and 64 channels
num_channels = 64
sampling_rate = 1000  # One second of data if sampling rate is 1000 Hz

# Calculate the total number of complete samples you can get
total_data_points = 320320
possible_samples = total_data_points / (num_channels * sampling_rate)

print("You can fit", possible_samples, "complete samples of 1 second each with your data.")


You can fit 5.005 complete samples of 1 second each with your data.


In [ ]:
num_data_points = 320320
common_channel_counts = [32, 64, 128]  # common EEG channel counts

# Check how the data points fit with each channel count
for channels in common_channel_counts:
    samples = num_data_points / channels
    print(f"With {channels} channels, you get {samples} samples.")



With 32 channels, you get 10010.0 samples.
With 64 channels, you get 5005.0 samples.
With 128 channels, you get 2502.5 samples.


In [ ]:
import numpy as np

# Load the data
data = pd.read_csv('/content/datafile-output1.csv').values

# Let's assume the number of channels is 64 and we now know the exact number of samples
num_channels = 64
num_samples = num_data_points / num_channels  # this should be an integer

# Reshape the data (ensure data is loaded correctly if it's not already a numpy array)
reshaped_data = np.array(data).reshape((int(num_samples), num_channels))

# Assuming the output of possible_samples is not a whole number and you truncate it
# num_complete_samples = int(possible_samples)  # Truncate to get only complete samples

# # Calculate the number of points that fit into complete samples
# points_to_use = num_complete_samples * num_channels * sampling_rate

# # Reshape the data
# reshaped_data = data[:points_to_use].reshape(num_complete_samples, sampling_rate, num_channels)

# # Reshape the data
# num_channels = 64  # example for 64 electrodes
# sampling_rate = 1000  # 1000 Hz sampling rate
# num_samples = data.shape[1] // (num_channels * sampling_rate)  # calculate number of samples

# reshaped_data = data.reshape(num_samples, sampling_rate, num_channels)


In [ ]:
reshaped_data

array([[ -925.25,  -781.75,  -773.75, ..., -1480.  , -8183.25, -8192.  ],
       [-1488.25, -1307.25, -1298.5 , ..., -1851.25,  -595.25, -8192.  ],
       [-1379.75, -1250.5 , -1238.  , ..., -1326.5 ,  8191.75,  8179.25],
       ...,
       [-1323.75, -1140.25, -1147.5 , ..., -1774.5 ,  3968.25, -8183.5 ],
       [-1213.  , -1073.5 , -1079.75, ..., -1130.  ,  8191.75,  8191.75],
       [ -668.5 ,  -586.5 ,  -601.75, ...,  -256.  ,  8191.75,  8187.75]])

In [ ]:
new_data = pd.DataFrame(reshaped_data)

In [ ]:
new_data.head(20)

0        1        2        3        4        5        6        7   \
0   -925.25  -781.75  -773.75  -856.25  -801.00  -798.25  -725.50  -704.50   
1  -1488.25 -1307.25 -1298.50 -1378.00 -1305.00 -1302.00 -1166.50 -1155.25   
2  -1379.75 -1250.50 -1238.00 -1280.25 -1204.00 -1206.25 -1081.50 -1080.50   
3   -864.50  -798.25  -788.75  -797.25  -755.00  -758.25  -663.25  -680.00   
4    -56.25   -59.75   -61.75   -39.25   -25.50   -26.75    -3.50   -24.75   
5    833.00   756.25   757.75   791.00   770.00   770.75   712.25   682.50   
6   1378.00  1284.75  1276.50  1301.75  1259.50  1252.25  1161.00  1113.75   
7   1270.50  1216.50  1210.00  1192.25  1150.50  1149.75  1058.25  1031.50   
8    780.75   780.75   775.75   734.75   704.75   708.25   639.25   634.50   
9     -7.75    61.25    60.75    -6.75    10.00    13.25    14.75    22.00   
10  -904.00  -755.25  -754.25  -840.50  -782.25  -783.25  -710.50  -683.75   
11 -1461.75 -1297.25 -1287.75 -1361.00 -1302.50 -1300.25 -1169.00 -1157.25   
12 -1356.75 -1255.50 -1241.50 -1268.00 -1210.00 -1212.00 -1078.50 -1066.25   
13  -863.75  -806.00  -796.75  -799.75  -760.00  -757.25  -673.25  -678.00   
14   -68.75   -76.25   -74.75   -47.50   -35.75   -38.50   -22.50   -34.25   
15   832.25   758.25   762.00   789.75   767.25   765.75   701.25   681.50   
16  1387.50  1290.50  1287.00  1307.50  1264.50  1262.75  1163.50  1130.50   
17  1289.25  1238.00  1236.50  1215.25  1188.50  1189.50  1105.00  1061.00   
18   752.00   767.50   763.00   712.00   686.50   683.00   627.25   601.75   
19   -40.00    34.25    33.00   -32.25   -22.50   -25.75   -14.75   -18.75   

         8        9   ...       54       55       56       57       58  \
0   -724.25  -800.75  ... -1213.75 -1131.00 -1124.50 -1234.00 -1229.50   
1  -1148.75 -1353.50  ... -1550.50 -1437.25 -1428.00 -1576.50 -1575.25   
2  -1071.50 -1235.00  ... -1151.75 -1060.50 -1049.00 -1169.75 -1167.50   
3   -655.50  -734.25  ...  -487.00  -461.25  -447.00  -521.00  -519.50   
4     -8.50    32.00  ...   526.75   495.25   497.75   486.75   490.50   
5    704.50   842.50  ...  1180.00  1082.75  1080.50  1133.00  1137.50   
6   1146.75  1315.50  ...  1523.50  1374.00  1365.00  1467.50  1463.00   
7   1043.25  1214.50  ...  1116.25  1009.75  1000.00  1078.00  1075.75   
8    631.25   732.75  ...   490.25   413.75   414.25   445.25   451.00   
9     14.00   -10.75  ...  -561.75  -524.25  -527.75  -562.75  -559.50   
10  -699.25  -835.25  ... -1243.50 -1134.25 -1133.00 -1239.75 -1231.25   
11 -1156.00 -1325.50  ... -1569.50 -1465.75 -1459.00 -1575.00 -1569.50   
12 -1075.25 -1225.50  ... -1134.75 -1102.00 -1091.75 -1156.75 -1152.75   
13  -666.00  -767.50  ...  -502.50  -476.00  -461.00  -530.50  -520.75   
14   -17.00   -16.00  ...   522.25   492.75   487.25   459.50   461.75   
15   693.00   816.50  ...  1204.00  1100.00  1093.50  1139.25  1136.00   
16  1152.00  1313.50  ...  1523.50  1388.00  1379.75  1461.75  1466.75   
17  1091.25  1262.75  ...  1132.00  1010.50  1004.00  1073.75  1070.75   
18   630.00   754.75  ...   449.00   391.75   388.00   416.50   418.00   
19    -8.50    30.25  ...  -553.25  -547.00  -543.25  -582.50  -578.00   

         59       60       61       62       63  
0  -1427.75 -1133.50 -1480.00 -8183.25 -8192.00  
1  -1788.00 -1426.25 -1851.25  -595.25 -8192.00  
2  -1288.75 -1035.25 -1326.50  8191.75  8179.25  
3   -532.00  -432.50  -552.00  8189.00  8173.50  
4    618.75   500.75   604.00  8185.75  8170.50  
5   1346.75  1084.50  1345.25  8182.75  8167.25  
6   1701.75  1363.75  1693.50  -378.00  8169.00  
7   1223.00   993.50  1192.50 -8192.00 -8192.00  
8    488.00   399.25   441.75 -8189.50 -8192.00  
9   -670.25  -541.25  -734.50 -8186.50 -8192.00  
10 -1407.00 -1142.75 -1487.75 -8183.25 -8192.00  
11 -1812.50 -1451.75 -1861.75  -932.75 -8192.00  
12 -1295.75 -1066.50 -1332.25  8191.75  8179.25  
13  -546.00  -447.75  -563.50  8189.00  8173.25  
14   603.00   498.50   595.75  8186.00  8170.75  
15  1362.25  10

In [ ]:
new_data.shape

(5005, 64)

In [ ]:
5005 * 64

320320

In [ ]:
new_data.to_csv('saved_new_data.csv')