In [1]:
import neo

reader = neo.BlackrockIO(filename='../../data/sample/datafile003.ns2')
blk = reader.read_block()

# blk contains all the data segments and signals


In [2]:
for seg in blk.segments:
    for asig in seg.analogsignals:
        print(asig)  # This will print out the signal object which contains data


[[  609.75   594.5    593.   ...   647.5  -8180.5  -8181.25]
 [  146.5    186.     191.25 ...    51.75 -8178.75 -8179.5 ]
 [ -230.75  -167.75  -170.5  ...  -403.75 -8177.25 -8178.  ]
 ...
 [  403.5    299.75   300.5  ...   454.25  8191.75  8190.75]
 [  821.     684.75   675.   ...   927.    8191.75  8189.75]
 [ 1073.25   932.     928.75 ...  1214.75  8191.75  8188.25]] uV


In [5]:
import pandas as pd

data = []  # This will hold all the data rows
for seg in blk.segments:
    for asig in seg.analogsignals:
        data.append(asig.magnitude.flatten())  # Convert data to a flat list

# Create a DataFrame and save to CSV
df = pd.DataFrame(data)
df.to_csv('../../data/sample_output/datafile-output1.csv', index=False)


In [6]:
data = pd.read_csv('../../data/sample_output/datafile-output1.csv')

In [7]:
data.head()

0      1      2       3      4      5      6      7       8       9  \
0  609.75  594.5  593.0  563.25  555.5  547.0  518.5  519.5  508.75  563.25   

   ...   320310  320311   320312   320313   320314   320315   320316   320317  \
0  ...  1099.75  1005.0  1005.75  1075.25  1069.25  1306.75  1017.25  1214.75   

    320318   320319  
0  8191.75  8188.25  

[1 rows x 320320 columns]

In [8]:
data.shape

(1, 320320)

In [9]:
# You mentioned you expected a sampling rate of 1000 Hz and 64 channels
num_channels = 64
sampling_rate = 1000  # One second of data if sampling rate is 1000 Hz

# Calculate the total number of complete samples you can get
total_data_points = 320320
possible_samples = total_data_points / (num_channels * sampling_rate)

print("You can fit", possible_samples, "complete samples of 1 second each with your data.")


You can fit 5.005 complete samples of 1 second each with your data.


In [10]:
num_data_points = 320320
common_channel_counts = [32, 64, 128]  # common EEG channel counts

# Check how the data points fit with each channel count
for channels in common_channel_counts:
    samples = num_data_points / channels
    print(f"With {channels} channels, you get {samples} samples.")



With 32 channels, you get 10010.0 samples.
With 64 channels, you get 5005.0 samples.
With 128 channels, you get 2502.5 samples.


In [12]:
import numpy as np

# Load the data
data = pd.read_csv('../../data/sample_output/datafile-output1.csv').values

# Let's assume the number of channels is 64 and we now know the exact number of samples
num_data_points = 320320
num_channels = 64
num_samples = num_data_points / num_channels  # this should be an integer

# Reshape the data (ensure data is loaded correctly if it's not already a numpy array)
reshaped_data = np.array(data).reshape((int(num_samples), num_channels))

# Assuming the output of possible_samples is not a whole number and you truncate it
# num_complete_samples = int(possible_samples)  # Truncate to get only complete samples

# # Calculate the number of points that fit into complete samples
# points_to_use = num_complete_samples * num_channels * sampling_rate

# # Reshape the data
# reshaped_data = data[:points_to_use].reshape(num_complete_samples, sampling_rate, num_channels)

# # Reshape the data
# num_channels = 64  # example for 64 electrodes
# sampling_rate = 1000  # 1000 Hz sampling rate
# num_samples = data.shape[1] // (num_channels * sampling_rate)  # calculate number of samples

# reshaped_data = data.reshape(num_samples, sampling_rate, num_channels)


In [13]:
reshaped_data

array([[  609.75,   594.5 ,   593.  , ...,    51.75, -8178.75, -8179.5 ],
       [ -230.75,  -167.75,  -170.5 , ...,  -867.25, -8175.75, -8176.5 ],
       [ -941.75,  -840.5 ,  -829.5 , ..., -1440.5 , -8172.75, -8173.25],
       ...,
       [ -695.25,  -705.25,  -691.25, ...,  -597.  ,  8191.75,  8191.75],
       [   54.5 ,   -31.5 ,   -30.  , ...,   454.25,  8191.75,  8190.75],
       [  821.  ,   684.75,   675.  , ...,  1214.75,  8191.75,  8188.25]])

In [14]:
new_data = pd.DataFrame(reshaped_data)

In [15]:
new_data.head(20)

0        1        2        3        4        5        6        7   \
0    609.75   594.50   593.00   563.25   555.50   547.00   518.50   519.50   
1   -230.75  -167.75  -170.50  -221.75  -203.50  -202.50  -174.00  -181.50   
2   -941.75  -840.50  -829.50  -876.00  -845.50  -845.75  -771.25  -780.00   
3  -1284.25 -1189.50 -1183.75 -1209.25 -1166.75 -1163.25 -1083.50 -1058.50   
4  -1145.50 -1077.25 -1066.75 -1066.25 -1029.75 -1027.50  -958.75  -944.00   
5   -634.50  -620.00  -614.75  -587.75  -569.75  -573.50  -540.00  -526.75   
6    226.00   129.00   130.00   194.50   189.50   188.00   171.75   184.75   
7    929.25   812.25   806.50   859.75   833.50   837.25   770.25   768.50   
8   1247.25  1161.00  1146.25  1166.25  1129.50  1132.00  1077.50  1018.50   
9   1114.50  1045.00  1037.00  1037.00  1011.25  1008.50   957.50   922.75   
10   621.50   608.25   605.00   579.25   575.75   564.25   535.50   518.50   
11  -226.00  -147.75  -145.50  -199.50  -191.00  -184.50  -163.75  -188.00   
12  -951.25  -840.00  -832.25  -893.50  -859.75  -851.75  -776.50  -783.25   
13 -1256.25 -1168.25 -1157.50 -1181.50 -1131.25 -1130.25 -1059.00 -1025.50   
14 -1119.00 -1040.00 -1034.25 -1043.25  -991.00  -994.50  -922.50  -910.50   
15  -632.75  -612.25  -605.75  -587.00  -570.75  -575.50  -536.75  -526.75   
16   246.25   154.75   155.50   220.50   196.00   201.75   179.75   190.50   
17   935.75   825.50   813.25   868.75   846.25   845.00   781.75   767.25   
18  1228.00  1135.00  1129.75  1154.75  1121.00  1120.00  1069.50  1005.75   
19  1117.50  1034.75  1020.75  1029.00  1005.00  1001.75   940.50   926.50   

         8        9   ...       54       55       56       57       58  \
0    508.75   563.25  ...   140.25   108.50   105.50   113.50   112.75   
1   -175.25  -224.25  ...  -688.00  -650.25  -640.50  -683.75  -675.50   
2   -769.50  -882.75  ... -1216.75 -1142.50 -1133.25 -1198.50 -1195.25   
3  -1075.25 -1227.75  ... -1400.25 -1305.50 -1291.00 -1360.50 -1359.25   
4   -954.25 -1086.50  ...  -896.25  -836.75  -821.25  -862.50  -861.75   
5   -538.50  -630.50  ...  -135.00  -142.00  -132.25  -116.75  -119.75   
6    163.75   180.75  ...   679.25   613.00   609.25   662.00   663.75   
7    760.75   874.50  ...  1202.75  1089.50  1085.50  1164.00  1162.00   
8   1059.25  1207.50  ...  1388.50  1258.25  1251.75  1327.25  1323.25   
9    943.75  1091.25  ...   843.50   761.25   756.75   818.50   819.00   
10   527.00   619.50  ...   120.25    96.50    91.25   106.25   108.00   
11  -168.75  -205.50  ...  -698.00  -669.25  -671.25  -699.50  -694.75   
12  -772.75  -918.50  ... -1214.75 -1139.50 -1134.50 -1194.75 -1190.50   
13 -1051.25 -1254.75  ... -1367.25 -1300.75 -1290.00 -1349.50 -1344.75   
14  -916.50 -1085.25  ...  -883.50  -833.75  -816.75  -849.50  -844.75   
15  -531.00  -561.25  ...  -138.00  -146.00  -134.00  -112.50  -107.50   
16   176.75   248.50  ...   675.00   611.00   610.00   673.00   666.00   
17   780.75   902.25  ...  1202.75  1102.25  1101.00  1173.50  1167.00   
18  1059.25  1193.50  ...  1340.25  1233.75  1240.00  1319.25  1309.50   
19   926.75  1073.75  ...   861.25   777.25   771.75   829.50   827.00   

         59       60       61       62       63  
0     69.00    89.75    51.75 -8178.75 -8179.50  
1   -836.50  -669.75  -867.25 -8175.75 -8176.50  
2  -1407.75 -1165.50 -1440.50 -8172.75 -8173.25  
3  -1579.50 -1309.25 -1600.25  8191.75 -2930.25  
4   -967.00  -821.50  -974.00  8191.75  8191.75  
5    -81.50  -125.75   -67.25  8191.75  8191.75  
6    816.00   628.00   830.00  8191.75  8191.75  
7   1372.50  1106.25  1391.50  8191.75  8191.75  
8   1538.50  1255.75  1542.75 -8185.00  2097.50  
9    908.75   757.50   906.00 -8182.00 -8182.75  
10    63.75    73.75    39.00 -8178.75 -8179.50  
11  -849.00  -691.50  -890.00 -8175.75 -8176.50  
12 -1401.00 -1163.25 -1439.50 -8172.50 -8173.25  
13 -1556.25 -1309.50 -1584.50  8191.75 -2634.00  
14  -953.00  -820.50  -954.50  8191.75  8191.75  
15   -80.75  -1

In [16]:
new_data.shape

(5005, 64)

In [17]:
5005 * 64

320320

In [18]:
new_data.to_csv('../../data/sample_output/saved_new_data.csv')